variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy

.backend:
  variables:
    ARTIFACTS_PATHS: "build/libs/*.jar"

build:
  stage: build
  extends: .backend
  script:
    - ./gradlew build
  artifacts:
    paths:
      - "$ARTIFACTS_PATHS"
    expire_in: 1 day

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  extends: .backend
  needs:
    - test
    - build
  script:
    - echo "Deploying application"
    - |
      $envVars = @(
        "DB_USERNAME=$DB_USERNAME",
        "DB_PASSWORD=$DB_PASSWORD",
        "JWT_SECRET=$JWT_SECRET"
      )
      $envVars | Out-File -FilePath .env -Encoding utf8
    - docker-compose down
    - docker-compose build
    - docker-compose up -d
  artifacts:
    paths:
      - .env

after_script:
  - echo "End CI"