# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_IMAGE: "ritovale/knockoutticketrepo"

stages:
  - build
# - test
  - dockerize
  - deploy

build:
  image: gradle:7.5.0-jdk17
  stage: build
  script:
    - gradle clean assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

test:
  image: gradle:7.5.0-jdk17
  stage: test
  script:
    - gradle test

dockerize:
  image: docker:19.03.12
  services:
    - docker:dind
  stage: dockerize
  before_script:
    - echo "Verifying DOCKER_HUB_USERNAME exists..."
    - if [ -z "$DOCKER_HUB_USERNAME" ]; then echo "Username is NOT set"; exit 1; else echo "Username is set"; fi
    - echo "Verifying DOCKER_HUB_PASSWORD exists..."
    - if [ -z "$DOCKER_HUB_PASSWORD" ]; then echo "Password is NOT set"; exit 1; else echo "Password is set"; fi
    - echo "Attempting to login to Docker Hub..."
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin

  script:

    - docker network create knockout_ticket_staging || echo "Network already exists or cannot be created"
    - docker pull mysql:5.7
    - docker run --net=knockout_ticket_staging --name knockoutticket-db -e MYSQL_DATABASE=knockoutticket_database -e MYSQL_ROOT_PASSWORD=240420042501 -p 3390:3306 -d mysql:5.7 || echo "MySQL container is already running or could not be started"
    - docker build -t $DOCKER_HUB_USERNAME/knockoutticketrepo:$CI_COMMIT_REF_SLUG .
    - docker push $DOCKER_HUB_USERNAME/knockoutticketrepo:$CI_COMMIT_REF_SLUG
  only:
    - development
  dependencies:
    - build

deploy:
  image: docker:19.03.12
  services:
    - docker:dind
  stage: deploy
  script:
    - echo "Deploying application from Docker Hub"
    - docker pull $DOCKER_HUB_USERNAME/knockoutticketrepo:$CI_COMMIT_REF_SLUG
    - |
      docker run -d -p 8090:8080 --net=knockout_ticket_staging --env SPRING_PROFILES_ACTIVE=staging --name= $DOCKER_HUB_USERNAME/knockoutticketrepo:$CI_COMMIT_REF_SLUG || echo "Deployment container could not be started"
  only:
    - development
