version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - knockoutticket-db
    networks:
      - knockoutticket-network


  knockoutticket-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 240420042501
      MYSQL_DATABASE: knockoutticket_database
    ports:
      - "3369:3306"
    networks:
      - knockoutticket-network

networks:
  knockoutticket-network:
    external: true


