version: '3.8'

services:
  knockoutticket-db:
    image: mysql:latest
    container_name: knockoutticket-db
    environment:
      MYSQL_ROOT_PASSWORD: 240420042501
      MYSQL_DATABASE: knockoutticket_database
    ports:
      - "3369:3306"

networks:
  knockoutticketbackend_default:
    external: true
