version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
    depends_on:
      - knockoutticket-db

  knockoutticket-db:
    image: mysql:latest
    container_name: knockoutticket-db
    environment:
      MYSQL_ROOT_PASSWORD: 240420042501
      MYSQL_DATABASE: knockoutticket_database
    ports:
      - "3369:3306"



