version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
    env_file:
      - .env
    depends_on:
      - knockout-staging-db
    networks:
      - knockout-network

  knockout-staging-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 240420042501
      MYSQL_DATABASE: knockoutticket_database
    ports:
      - "3369:3306"
    networks:
      - knockout-network

networks:
  knockout-network:
    external: true